language: 'php'
php:
    - '7.3'

cache:
    directories:
        - $HOME/composer/cache

before_install: true

install:
    - composer install

before_script:
    - phpunit tests

script: true
    - ./vendor/bin/php-cs-fixer fix --dry-run --diff --verbose
    - phpunit tests

after_script: true